config/routes.rb
Rails.application.routes.draw do
    root 'tasks#index'
    resources :labels

    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :show, :edit, :update, :index]
    
    namespace :admin do
      resources :users, except: [:show]
    end

    resources :tasks do
      collection do
        post :sort
        get :search
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings, source: :label
  belongs_to :user, optional: true

  validates :name, presence: true, length: {maximum: 120}
  validates :detail, presence: true, length: {maximum: 1000}
  validates :deadline, presence: true

  enum status: {
    未着手: 0,
    着手中: 1,
    完了: 2
  }

  enum priority: {
    高: 0,
    中: 1,
    低: 2
  }

  # sort by created_at
  scope :sorted, -> { order(created_at: :desc) }
  # sort by status
  scope :status_sort, -> (search_status){ where(status: search_status) }
  scope :priority_sort, -> { order(priority: :asc) }
  scope :deadline_sorted, -> { order(deadline: :desc) }
  scope :label_sort, -> (search_label){
    tasks = Labeling.where(label_id: search_label)
    ids = tasks.map{ |task| task.task_id }
    where(id: ids)
  }

  # seach by name/word
  scope :search_sort, -> (search_word){ where('name LIKE ?', "%#{search_word}%") }  
  scope :kaminari, -> (kaminari_page){ page(kaminari_page).per(10) }
  scope :current_user_sort, -> (current_user_id){ where(user_id: current_user_id) }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only:  %i[ show edit update destroy ]
  before_action :authenticate_user

  def authenticate_user
    @current_user = User.find_by(id: session[:user_id])
    if @current_user.nil?
      redirect_to new_session_path
    end
  end

  def index
    @tasks = current_user.tasks.sorted.kaminari(params[:page])
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
    @tasks = @tasks.reorder(priority: :desc) if params[:priority_sort]
  end

  def new
    @task = Task.new
    @label = @task.labelings.build
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  def edit
    @labels = Label.where(user_id: 9).or(Label.where(user_id: current_user))
  end

  def sort
    @tasks = searched
    @search_name = session[:search]['name']  if session[:search].present?
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    @tasks =
      if params[:sort] == 'created_at'
        @tasks.sorted
      elsif params[:sort] == 'deadline'
        @tasks.deadline_sorted
      elsif params[:sort] == 'priority'
        @tasks.priority_sort          
      end
    session[:search] = nil
    render :index
  end

  def search
    session[:search] = {'name' => params[:search_name], 'status' => params[:search_status], 'priority' => params[:search_priority], 'label' => params[:search_label]}
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    @tasks = searched
    @tasks = @tasks.sorted
    @search_name = session[:search]['name']
    render :index
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
      if @task.save
        redirect_to tasks_path, notice: "Task was successfully created."
      else
        render :new
      end
    end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "Task was successfully updated."
    else
      render :edit
    end
  end

  def confirm
    @task= Task.new(task_params)
    render :new if @task.blank?
  end

  def show
    @task= Task.find(params[:id])
    @labels = Label.where(user_id: 9).or(Label.where(user_id: current_user))
  end
  
  def destroy
    @task.destroy
    redirect_to tasks_url, notice:"Task was successfully destroyed."
    end
  end  

  private  
  def task_params
    params.require(:task).permit(
      :name, 
      :detail, 
      :deadline, 
      :status, 
      :priority,
      label_ids: []
    )
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def correct_user
    if current_user.id != @task.user_id
      redirect_to tasks_path
    end
  end

  def searched
    if session[:search].present?
      # all blank
      if session[:search]['name'].blank? && session[:search]['status'].blank? && session[:search]['priority'].blank? && session[:search]['label'].blank?
        Task.current_user_sort(current_user.id).kaminari(params[:page])
      # name = present
      elsif session[:search]['name'].present?
        # status & priority & label = present 
        if session[:search]['status'].present? && session[:search]['priority'].present? && session[:search]['label'].present?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).status_sort(session[:search]['status']).priority_sort(session[:search]['priority']).label_sort(session[:search]['label']).kaminari(params[:page])
        # status & priority  = present
        elsif session[:search]['status'].present? && session[:search]['priority'].present?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).status_sort(session[:search]['status']).priority_sort(session[:search]['priority']).kaminari(params[:page])
        # status & label  = present
        elsif session[:search]['status'].present? && session[:search]['label'].present? && session[:search]['priority'].blank?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).status_sort(session[:search]['status']).label_sort(session[:search]['label']).kaminari(params[:page])
        # priority & label  = present 
        elsif session[:search]['priority'].present? && session[:search]['label'].present? && session[:search]['status'].blank?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).priority_sort(session[:search]['priority']).label_sort(session[:search]['label']).kaminari(params[:page])
        # status  = present
        elsif session[:search]['status'].present? && session[:search]['priority'].blank? && session[:search]['label'].blank?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).status_sort(session[:search]['status']).kaminari(params[:page])
        #  priority = present 
        elsif session[:search]['priority'].present? && session[:search]['status'].blank? && session[:search]['label'].blank?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).priority_sort(session[:search]['priority']).kaminari(params[:page])
        # label  = present 
        elsif session[:search]['label'].present? && session[:search]['status'].blank? && session[:search]['priority'].blank?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).label_sort(session[:search]['label']).kaminari(params[:page])
        #  name  = present 
        else
          Task.current_user_sort(current_user.id).search_sort(session[:search]['name']).kaminari(params[:page])
        end
  
      elsif session[:search]['status'].present?
  
        if session[:search]['priority'].present? && session[:search]['label'].present?
          Task.current_user_sort(current_user.id).status_sort(session[:search]['status']).priority_sort(session[:search]['priority']).label_sort(session[:search]['label']).kaminari(params[:page])
  
        elsif session[:search]['priority'].present? && session[:search]['label'].blank?
          Task.current_user_sort(current_user.id).status_sort(session[:search]['status']).priority_sort(session[:search]['priority']).kaminari(params[:page])
  
        elsif session[:search]['label'].present? && session[:search]['priority'].blank?
          Task.current_user_sort(current_user.id).status_sort(session[:search]['status']).label_sort(session[:search]['label']).kaminari(params[:page])
  
        else
          Task.current_user_sort(current_user.id).status_sort(session[:search]['status']).kaminari(params[:page])
        end
  
      elsif session[:search]['priority'].present?
  
        if session[:search]['label'].present?
          Task.current_user_sort(current_user.id).priority_sort(session[:search]['priority']).label_sort(session[:search]['label']).kaminari(params[:page])
  
        else
          Task.current_user_sort(current_user.id).priority_sort(session[:search]['priority']).kaminari(params[:page])
        end
  
      elsif session[:search]['label'].present?
        Task.current_user_sort(current_user.id).label_sort(session[:search]['label']).kaminari(params[:page])
      end
    else
      Task.current_user_sort(current_user.id).kaminari(params[:page])
    end
  end
  

app/helpers/tasks_helper.rb
module TasksHelper  
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
          <% task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
<br>
  <div class="field">
      <p> <%= form.label :priority %> </p>
      <p><%= form.select :priority, Task.priorities.keys %></p>
  </div>  
  <div class="field">
    <p> <%= form.label :status %> </p>
    <p><%= form.select  :status, Task.statuses.keys %></p>
  </div>
  <div class="field">
      <p> <%= form.label :name %> </p>
      <p><%= form.text_field :name %> </p>
  </div>
  <div class="field">
      <p> <%= form.label :detail %> </p>
      <p><%= form.text_area :detail, size: "23x5" %> </p>
  </div> 
  <div class="field">
      <p> <%= form.label :deadline %> </p>
      <p><%= form.date_select :deadline,
        use_month_numbers: true,
        start_year: Time.current.year,
        end_year: Time.current.year + 10,
        default: DateTime.now %> </p>
  </div>
  <div class="field">
      <p> <%= form.label :label %></p>      
      <p class="label_list"><%= form.collection_check_boxes(:label_ids, Label.all, :id, :name)  %> </p>
  </div>      
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit my task</h1>
<br>
<th class="user">Made by <%= @task.user.name%></th>
<br><br>
<%= link_to 'Back', tasks_path, class: "button_link"  %>
<br>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<div class="notifications">
  <div class="notice">
    <p id="notice"><%= notice %></p>
  </div>
</div>
<div class="danger"><%= flash[:danger] %></div>

<%= link_to 'New label', new_label_path, class: 'button_signup'%>
<%= link_to 'New task', new_task_path, class: 'button_signup'%>
<br>

<div class="table_frame">
  <table>
    <tr>
      <th class="th_label">Label</th>
      <th class="th_label">User</th>
      <th class="th_label">Date </th>
      <th class="th_label">Priority</th>
      <th class="th_label">Status</th>
      <th class="th_label">Deadline</th>
      <th class="th_label">Name</th>
      <th class="th_label">Detail</th>
    </tr>       

  <div class="search_form">
    <%= form_with(url: search_tasks_path, method: :get, local: true) do %>      
      <%= select_tag :search_status, options_for_select([['未着手'],['着手中'],['完了']]),
        { class: 'search_select', prompt: 'ステータス' } %>
      <%= text_field_tag :search_name %>
      <%= submit_tag 'タスク検索' %>
    <% end %>
  </div><br>

  <div class="sort_search">
    <%= form_with(url: sort_tasks_path, local: true) do |f| %>
      <%= select_tag :sort, options_for_select([["Sort by created time","created_at"],["Sort by deadline","deadline"],["Sort by priority","priority"]]), { class: 'sort_select' } %>
      <%= submit_tag "ソート" %>
    <% end %>  
  
  <%= form_with url: tasks_path, method: :get, local: true do |form| %>
    <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
    <%= form.submit 'ラベル検索', name: nil %>
  <% end %> </div> 
  <br><br>

  <tr >
    <% if @tasks.present? %>
      <% @tasks.each do |task| %>
        <% if task.user_id == current_user.id %>
            <th class="label">
             <% task.labels.each do |label| %>
              <th class="label"><%= label.name %>
            <% end %> 
            <th class="user"><%= task.user.name%></th>
            <th class="created_at"><%= task.created_at.to_s(:datetime)%></th>
            <th class="button"><%= task.priority%></th>
            <th class="status"><%= task.status %></th>
            <th class="button"><%= task.deadline %></th>
            <th class="task_row"><%= task.name %></th>
            <th class="task_detail"><%= task.detail %></th>
            <th colspan="3"> 
              <td><%= button_to 'Delete', task_path(task.id), method: :delete, data: {confirm: "Are you sure?"}, class: "button" %></td>
              <td><%= button_to 'Detail', task_path(task.id),  method: :get, class: "button" %></td>
              <td><%= button_to "Edit", edit_task_path(task.id),  method: :get, class: "button" %></td> 
            </th></tr>  
        <% end %>
      <% end %>
    <% else %>
      <%= '検索結果に該当するタスクはありません' %>
    <% end %>
  </table>

  <% if @tasks.present? %>
    <div class="page">
      <%= paginate @tasks %>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1><%=current_user.name%>'s new Task</h1>

<%= render 'form', task: @task %>
<%= link_to 'Back', tasks_path, class: 'button_link' %>
<br> <br>

app/views/tasks/show.html.erb
<h1>Detail</h1>
<br>
<p><%= link_to 'Back', tasks_path , class: "button_link"%></p>
<br>
<div class="table_frame">
  <table>
    <tr>
      <th class="th_label">Label</th>
      <th class="th_label">User</th>
      <th class="th_label">Date </th>
      <th class="th_label">Priority</th>
      <th class="th_label">Status</th>
      <th class="th_label">Deadline</th>
      <th class="th_label">Title</th>
      <th class="th_label">Detail</th>
    </tr>
           
    <tr>    
        <th class="label">
          <% @task.labels.each do |label| %>
        <th class="label"><%= label.name %>
          <% end %></th>           
        <th class="user"><%= @task.user.name%></th>
        <th class="created_at"><%= @task.created_at.to_s(:datetime)%></th>
        <th class="button"><%= @task.priority%></th>
        <th class="status"><%= @task.status%></th>
        <th class="button"><%= @task.deadline%></th>
        <th class="th_title"><%= @task.name%></th>
        <th class="th_detail"><%= @task.detail%></th>
        <th colspan="3"> 
        <td><%= button_to 'Delete', task_path(@task.id), method: :delete, data: {confirm: "Are you sure?"}, class: "button" %></td>
        <td><%= button_to 'Detail', task_path(@task.id),  method: :get, class: "button" %></td>
        <td><%= button_to "Edit", edit_task_path(@task.id),  method: :get, class: "button" %></td>
        </th>            
        
    </tr>              
  </table>
</div>
<br>