config/routes.rb
Rails.application.routes.draw do
    root 'tasks#index'
    resources :labels

    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :show, :edit, :update, :index]
    
    namespace :admin do
      resources :users, except: [:show]
    end

    resources :tasks do
      collection do
        post :sort
        get :search
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  before_destroy :destroy_action
  before_update :update_action

  has_secure_password
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 120 }
  validates :email, presence: true, length: { maximum: 250 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  private
  def destroy_action
    if User.where(admin: true).count == 1 && self.admin? == true
      errors.add(:admin,'なので削除できません。最低一人の管理者が必要です')
      throw(:abort)
    end
  end

  def update_action
    user = User.where(id: self.id).where(admin: true)
    if User.where(admin: true).count == 1 && user.present? && self.admin == false
      errors.add(:admin,'から外せません。最低一人の管理者が必要です')
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit,:update, :destroy]
  before_action :admin_user

  def index
    @users = User.all.includes(:tasks)
    @users = User.all.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "#{@user.name}さんのアカウントを作成しました"
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "#{@user.name}さんのデータを更新しました"
    elsif @user.errors.any? 
      render :edit, notice: "管理権を外せません。最低一人の管理者が必要です"
    end
  end

  def destroy
    if @user.destroy
    redirect_to admin_users_path, notice: "#{@user.name}さんのデータを削除しました"
    elsif @user.errors.any? 
      redirect_to admin_users_path, notice: "削除できません。最低一人の管理者が必要です"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def admin_user
    unless current_user.admin?
      redirect_to tasks_path
      flash[:notice] = '管理者の権限が必要です！'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [:new, :create], raise: false
  before_action :correct_user?, only: %i[ show ]

  def index
    @users = User.all
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  def correct_user?
    @user = User.find_by(id: params[:id])
    unless current_user.admin?
      if current_user.id != @user.id
        flash[:danger] = "権限がありません"
        redirect_to root_path
      end
    end
  end

  def new
    @user = User.new
    if logged_in?
      redirect_to tasks_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @tasks = Task.all
    @tasks = @tasks.page(params[:page])
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "Your informations have been updated!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password_digest, :password, :password_confirmation, :email)
  end  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def admin?
    current_user.admin if logged_in?
  end
  def choose_admin_path
    if action_name == "new"
      admin_users_path
    else
      admin_user_path(@user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    current_user.admin
  end
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit my account</h1>
<%= render 'form', user: @user %>
  <%= form_with(model: @user, local: true ) do |f| %>
    <form class="login-container">
      <p><%= f.label "Name" %></p>
      <p><%= f.text_field :name %></p>
      <p><%= f.label "Email" %></p>
      <p><%= f.text_field :email %></p>
      <p><%= f.label "Password"  %></p>
      <p><%= f.password_field :password %></p>
      <p><%= f.label "Password confirmation"  %></p>
      <p><%= f.password_field :password_confirmation %></p>
      <p><%= f.submit "Submit" %></p>
    </form>
    <% end %>
<%= link_to 'Back', user_path(current_user.id),class:"button_link" %> 
<br><br><br>

app/views/users/index.html.erb
<h1>Users</h1>
<div class="notifications">
 <div class="notice">
  <p id="notice"><%= notice %></p>
  </div>
</div>

<table class="user_index">
  <thead>
    <tr>
      <th class="user_th1">Name</th>
      <th class="user_th2">Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td class="user_email"><%= user.email %></td>        
        <% if current_user.id == user.id %>
        <td class="user_td1"><%= link_to 'Show', user , class:"button" %></td>
        <td class="user_td1"><%= link_to 'Edit', edit_user_path(user) , class:"button" %></td>
        <td class="user_td1"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } , class:"button" %></td>
        <% end %>          
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= button_to 'New User', new_user_path , method: :get, class:"button_link" %>
<%= link_to 'Back',user_path(current_user.id),class:"button_link" %> 
<br><br><br>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form', user: @user %>
<%= form_with(model: @user, local: true) do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.label :email %></p>
<p><%= f.email_field :email %></p>
<p><%= f.label :password %></p>
<p><%= f.password_field :password %></p>
<p><%= f.label :password_confirmation %></p>
<p><%= f.password_field :password_confirmation %></p><br>
<p><%= f.submit "Create my account" %></p>
<% end %>
<%= link_to 'Back', root_path ,class:"button_link" %> 
<br><br><br>


app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
  <div class="notifications">
    <div class="notice">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
  <div class="danger"><%= flash[:danger] %></div>
<%= button_to "Edit my account", edit_user_path, method: :get, class:"button_signup" %>
<p>メールアドレス: <%= @user.email %></p>
<%= button_to "Make new task", new_task_path, method: :get, class:"button_link" %>
<br>
<div class="table_frame">
  <table>
    <tr>
      <th class="th_label">Label</th>
      <th class="th_label">User</th>
      <th class="th_label">Date </th>
      <th class="th_label">Priority</th>
      <th class="th_label">Status</th>
      <th class="th_label">Deadline</th>
      <th class="th_label">Name</th>
      <th class="th_label">Detail</th>
    </tr>       
    <tr>
      <% @tasks.each do |task| %>
          <% if task.user_id == @user.id %>
            <% if task.present? %>
                <th class="label">
                  <% task.labels.each do |label| %>
                  <th class="label"><%= label.name %>
                <% end %> </th>                 
                <th class="user"><%= task.user.name%></th>
                <th class="created_at"><%= task.created_at.to_s(:datetime)%></th>
                <th class="button"><%= task.priority%></th>
                <th class="status"><%= task.status %></th>
                <th class="button"><%= task.deadline %></th>
                <th class="task_row"><%= task.name %></th>
                <th class="task_detail"><%= task.detail %></th>
                <th colspan="3"> 
                <td><%= button_to 'Delete', task_path(task.id), method: :delete, data: {confirm: "Are you sure?"}, class: "button" %></td>
                <td><%= button_to 'Detail', task_path(task.id),  method: :get, class: "button" %></td>
                <td><%= button_to "Edit", edit_task_path(task.id),  method: :get, class: "button" %></td> </th></tr>            
             <% end %>
          <% end %>
        <% end %>
  </table>

  <% if @tasks.present? %>
    <div class="page">
      <%= paginate @tasks %>
    </div>
  <% end %>
</div>
<br>
<%= link_to 'Back', user_path(current_user.id),class:"button_link" %> 
<br><br><br>