config/routes.rb
Rails.application.routes.draw do
    root 'tasks#index'
    resources :labels

    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :show, :edit, :update, :index]
    
    namespace :admin do
      resources :users, except: [:show]
    end

    resources :tasks do
      collection do
        post :sort
        get :search
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  before_destroy :destroy_action
  before_update :update_action

  has_secure_password
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 120 }
  validates :email, presence: true, length: { maximum: 250 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  private
  def destroy_action
    if User.where(admin: true).count == 1 && self.admin? == true
      errors.add(:admin,'なので削除できません。最低一人の管理者が必要です')
      throw(:abort)
    end
  end

  def update_action
    user = User.where(id: self.id).where(admin: true)
    if User.where(admin: true).count == 1 && user.present? && self.admin == false
      errors.add(:admin,'から外せません。最低一人の管理者が必要です')
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit,:update, :destroy]
  before_action :admin_user

  def index
    @users = User.all.includes(:tasks)
    @users = User.all.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "#{@user.name}さんのアカウントを作成しました"
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "#{@user.name}さんのデータを更新しました"
    elsif @user.errors.any? 
      render :edit, notice: "管理権を外せません。最低一人の管理者が必要です"
    end
  end

  def destroy
    if @user.destroy
    redirect_to admin_users_path, notice: "#{@user.name}さんのデータを削除しました"
    elsif @user.errors.any? 
      redirect_to admin_users_path, notice: "削除できません。最低一人の管理者が必要です"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def admin_user
    unless current_user.admin?
      redirect_to tasks_path
      flash[:notice] = '管理者の権限が必要です！'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [:new, :create], raise: false
  before_action :correct_user?, only: %i[ show ]

  def index
    @users = User.all
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  def correct_user?
    @user = User.find_by(id: params[:id])
    unless current_user.admin?
      if current_user.id != @user.id
        flash[:danger] = "権限がありません"
        redirect_to root_path
      end
    end
  end

  def new
    @user = User.new
    if logged_in?
      redirect_to tasks_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @tasks = Task.all
    @tasks = @tasks.page(params[:page])
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "Your informations have been updated!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password_digest, :password, :password_confirmation, :email)
  end  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def admin?
    current_user.admin if logged_in?
  end
  def choose_admin_path
    if action_name == "new"
      admin_users_path
    else
      admin_user_path(@user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    current_user.admin
  end
end

app/views/admin/users/edit.html.erb
<h1>管理者用　ユーザー編集画面</h1>

<%= form_with(model: @user, url: admin_user_path(@user.id),  local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>            
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <br><%= form.label :name, '名前' %>
  <br><%= form.text_field :name %>

  <br><%= form.label :email, 'メールアドレス' %>
  <br><%= form.text_field :email %>

  <br><%= form.label :password, 'パスワード' %>
  <br><%= form.password_field :password %>

  <br><%= form.label :password_confirmation, 'パスワード確認' %>
  <br><%= form.password_field :password_confirmation %><br>        

  <br><%= form.label :管理者権限 %>
      <%= form.hidden_field :admin, value: false %>                  
  <br><%= form.check_box :admin, {}, true, false %>                  

  <br><%= form.submit %>            

<% end %>
<br>
<%= link_to 'Show', @user, class:"button_link" %> 
<br>
<%= link_to 'Back', admin_users_path, class:"button_link" %>
<br><br>

app/views/admin/users/index.html.erb
<h1>管理者画面</h1>
<br>
<div class="container">
  <%= link_to 'Make new user', new_admin_user_path, class:"button_link" %><br><br>  

  <div class="notifications">
    <div class="notice">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
  <div class="danger"><%= flash[:danger] %></div>

  <div class="users">
    <table>
      <% @users.each do |user| %>
        <tr>
          <th class = "user_all">
            <%= link_to user.name, user_path(user.id) %>
          </th>
          <th class = "task_count">
            タスク数:&nbsp;<%= user.tasks.count %>
          </th>
          <th class = "role">
            管理権:&nbsp;<%= user.admin%>
          </th>
          <th colspan="2", class = "user_option">
            <td><%= button_to 'Edit', edit_admin_user_path(user.id), method: :get, class:"button" %></td>
            <td><%= button_to 'Destroy', admin_user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"button" %></td>
          </th>
        </tr>
      <% end %>
    </table>
  </div>
</div>
  <% if @users.present? %>
    <div class="page">
      <%= paginate @users %>
    </div>
  <% end %>
<br><br>

app/views/admin/users/new.html.erb
<h1>管理者用　新規ユーザー登録</h1>

<%= form_with(model: @user, url: admin_users_path,  local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br><%= form.label :name, '名前' %>
  <br><%= form.text_field :name %>

  <br><%= form.label :email, 'メールアドレス' %>
  <br><%= form.text_field :email %>

  <br><%= form.label :password, 'パスワード' %>
  <br><%= form.password_field :password %>

  <br><%= form.label :password_confirmation, 'パスワード確認' %>
  <br><%= form.password_field :password_confirmation %>

  <br><%= form.label :管理者権限 %>
  <%= form.hidden_field :admin, value: false %>                  
  <br><%= form.check_box :admin, {}, true, false %>        

  <br><br><%= form.submit %>
<% end %>

<br><%= link_to 'Back', admin_users_path, class:"button_link" %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @task.detail %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<br><%= link_to 'Edit', edit_task_path(@task), class:"button_link" %> |

<br><%= link_to 'Back', tasks_path, class:"button_link" %>