config/routes.rb
Rails.application.routes.draw do
    root 'tasks#index'
    resources :labels

    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :show, :edit, :update, :index]
    
    namespace :admin do
      resources :users, except: [:show]
    end

    resources :tasks do
      collection do
        post :sort
        get :search
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Tasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width">  
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav>
        <ul class="top_menu clearfix">
          <li class="left">            
              <%= button_to "My Task", root_path, method: :get, class: 'button_header' %>
          </li>
          <div class="b-right">
            <li class="right">
              <%= button_to "Home", root_path, method: :get, class: 'button_header' %>
            </li>            
            <% if logged_in? %>
              <% if admin? %>
                <li class="right">
                  <%= link_to "Admin", admin_users_path, class: 'button_header' %>
                </li>
                <li class="right">
                  <%= link_to "Profile", user_path(current_user.id), class: 'button_header' %>
                </li>
                <li class="right">
                  <%= button_to "Logout", session_path(current_user.id), method: :delete,class: 'button_header' %>
                </li>
              <% else %>
                <li class="right">
                  <%= link_to "Profile", user_path(current_user.id), class: 'button_header' %>
                </li>
                <li class="right">
                  <%= button_to "Logout", session_path(current_user.id), method: :delete,class: 'button_header' %>
                </li>
              <% end %>
            <% else %>
              <li class="right">
                <%= link_to "Sign up", new_user_path,class: 'button_header'%>
              </li>
              <li class="right">
                <%= link_to "Login", new_session_path, class: 'button_header' %>
              </li>
            <% end %> 
            </div>           
          </ul>
      </nav>
    </header>
  <%= yield %>
  <footer>
    <p>運営会社 Remi 株式会社</p>
    <p>© 2022 Remi Corp.</p>
  </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>  
</html>